### ISSUE TITLE
Mobile support 

### ISSUE THREAD

**Issue by chirag127** [nkrishnaswami/open-selected-links#8]
It doesn't seems to open all the links on selection on https://www.amazon.in/gp/most-gifted/ref=zg_mg_unv_luggage_0_1 while using the extension in kiwi browser.

**Comment by nkrishnaswami** [comment]
Hi Chirag, thanks for the report! Can you describe how to reproduce this, once I install Kiwi + the extension? (I'm not sure what I'd need to do that's equivalent to a right click, eg)
Thanks, N.

**Comment by chirag127** [comment]
> Hi Chirag, thanks for the report! Can you describe how to reproduce this, once I install Kiwi + the extension? (I'm not sure what I'd need to do that's equivalent to a right click, eg) Thanks, N.

For equivalent of the right click, I'm clicking the extension.
